---
spring:
  application:
    name: spring-cloud-consul-consumer
---
server:
  port: 8503
---
spring:
  cloud:
   consul:
    host: 127.0.0.1
    port: 8500
  #\u8BBE\u7F6E\u4E0D\u9700\u8981\u6CE8\u518C\u5230 consul \u4E2D
    discovery:
     register: false